### PR TITLE
Add max heap space to yarn build

### PR DESCRIPTION
**Pull request by lukecookssw**
- [ ] Recommended extensions have been installed if using VS Code

### CODE REVIEW

**Comment by bradystroud** [comment]
Hey @jianganna7 @lukecookssw, 

I believe the problem is very similar to the one discussed in #829 
If it is, Increasing the memory size will only make it fail slower.

If you haven't already, I would reccommend following these debugging steps:

1. Create a branch off SSW.Rules.Conten:main for testing
1. Roll it back to the commit just before builds started to fail
1. Try building locally using that branch
1. If the build succeeds, the problem is definitely content related
1. Add commits (from main) to that branch until builds start to fail - this will help you determine the exact commit causing problems
1. Revert this commit on main
1. Investigate which change from that commit caused the OOM error
1. Update #829 

Good luck :)

**Comment by jianganna7** [comment]
> 1. Create a branch off SSW.Rules.Conten:main for testing, 2. Roll it back to the commit just before builds started to fail, 3. Try building locally using that branch, 4. If the build succeeds, the problem is definitely content related

Hey @bradystroud, I should mention that `SSW.Rules` on `fix/yarn-cd` or the `main` branch all succeeds building locally with the latest content on the `main` branch of `SSW.Rules.Content`. It only fails in DevOps pipeline.

**Comment by jianganna7** [comment]
> > 1. Create a branch off SSW.Rules.Conten:main for testing, 2. Roll it back to the commit just before builds started to fail, 3. Try building locally using that branch, 4. If the build succeeds, the problem is definitely content related
> 
> Hey @bradystroud, I should mention that `SSW.Rules` on `fix/yarn-cd` or the `main` branch all succeeds building locally with the latest content on the `main` branch of `SSW.Rules.Content`. It only fails in DevOps pipeline.

@bradystroud actually no... wrong branch. The `SSW.Rules` was linked to the default `sample-content-with-guid`, just changed to `fix/yarn-cd` and the build failed locally. I'll follow those steps above and update you and Luke on this.

**Comment by jianganna7** [comment]
Hey @bradystroud @lukecookssw,

So... it turns out there was an extra space in `line 95` in PR [improving readability + fix markdown #3097](https://github.com/SSWConsulting/SSW.Rules.Content/pull/3097) from `SSW.Rules.Content` that has caused the OOM error.

The OOM issue should now be fixed in [Fix OOM - Delete extra space in newline #3110](https://github.com/SSWConsulting/SSW.Rules.Content/pull/3110) without allocating more memories to the node.

**Comment by JackDevAU** [comment]
Anna solved the issue ⭐

**Pull request closed without merging**
