### PR TITLE
Update style.css to fix boxes

### PR DESCRIPTION
**Pull request by tiagov8**
@jeoffreyfischer 

This is to replace the script created on https://github.com/SSWConsulting/SSW.Rules/pull/1407/files

Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1397

### CODE REVIEW

**Comment by jeoffreyfischer** [comment]
Hi @tiagov8, as per our conversation, please delete lines 97 to 119 inside the tailwind.config file to avoid conflict with the CSS changes you've made.
These lines are responsible for the "heading inside boxes" style - which wasn't working anyway 🫠

image
**Figure: Lines to remove in tailwind.config**

**Comment by jeoffreyfischer** [comment]
In addition, you can also remove the zeroMarginStyles as it was only used by the "heading inside box" styles

image
**Figure: other lines that can be removed**

**Comment by tiagov8** [comment]
Hi @jeoffreyfischer 

Both blocks of lines were deleted

1. Please review again

**Review by jeoffreyfischer — APPROVED** [review]
LGTM

**Pull request merged**
