### PR TITLE
💄 Rule Page - Updated last modified by text

### PR DESCRIPTION
**Pull request by BrookJeynes**
As per my conversation with @jaydenalchin, I have gone and updated the last modified text for each rule

image

Related #217

### CODE REVIEW

**Comment by tiagov8** [comment]
Hey @BrookJeynes 

1. I'm OK removing the words 'view history' but I think the icon would work better **before** the text in this case
2. I think I prefer the divisor between Created and Last Updated to be a pipe `|` instead of a full stop `.`
3. I personally prefer to see the Last Updated in the format of "X hours/days ago" than in "DD MM YYYY"
4. I also think the reading is better if the Last Updated Author comes before the Date

Basically my recommendation is to make it be:

🕒 Created on 23 Jun 2022 | Last updated by **Seth Daily** 18 days ago

--

As per my comment on the related Issue: https://github.com/SSWConsulting/SSW.Rules/issues/217#issuecomment-1163419321

💡 Idea: An extra funcionality that I just thought about... What if the "X days/months ago" would show as a tooltip when hovering the last updated date? This way this metadata line is cleaner and shorter

**Review by tiagov8 — COMMENTED** [review]
Please see my comment: https://github.com/SSWConsulting/SSW.Rules/pull/1029#issuecomment-1607723627

**Comment by bradystroud** [comment]
> 💡 Idea: An extra funcionality that I just thought about... What if the "X days/months ago" would show as a tooltip when hovering the last updated date? This way this metadata line is cleaner and shorter

I like this idea - GitHub does this and it works pretty well

**Review by bradystroud — DISMISSED** [review]

**Comment by BrookJeynes** [comment]
As per my conversation with @tiagov8, we will be going ahead with the following design

image

**Comment by jaydenalchin** [comment]
> As per my conversation with @tiagov8, we will be going ahead with the following design
> 
> image

@tiagov8 @BrookJeynes 

I love the tooltip UX - but for the record I would prefer the date format be consistent between date created and date last updated. E.g. Created 6 years ago, last updated by Kiki 1 year ago.

**Comment by tiagov8** [comment]
> I love the tooltip UX - but for the record I would prefer the date format be consistent between date created and date last updated. E.g. Created 6 years ago, last updated by Kiki 1 year ago OR Created 15 Oct 2021 last updated by Kiki 10 Nov 2021 (tooltip over 1 year ago).

IMO the actual date works as a better reference for when something was created (every blog and articles will have it)

On the other hand... the "last updated" is just giving an idea of how recently that content has been looked after, so "XX months ago" makes it easier to quickly capture that sense of time...

But not a strong opinion so happy to change if others agree

**Comment by BrookJeynes** [comment]
As per my conversation with @bradystroud @tiagov8 and @jaydenalchin, here is the new implemented design

image

**Review by bradystroud — APPROVED** [review]
lgtm 🛶

**Review by jaydenalchin — APPROVED** [review]
LGTM 🚀

**Pull request merged**
