### PR TITLE
♻️ Improve User Filter

### PR DESCRIPTION
**Pull request by Aibono1225**
Relates to https://github.com/SSWConsulting/SSW.Rules/issues/1046#issuecomment-1739814861

Changes made:
- Updated page title
- Replaced pagination with "load more"
- Changed the url to `https://ssw.com.au/rules/user/?author={github login name}`
- Added "ago" after the timestamp
- Added another list to show acknowledgement

image
**Figure: is the title `{{ USER NAME }}'s Acknowledged Rules` good enough? 🤔**

### CODE REVIEW

**Comment by tiagov8** [comment]
Hey @Aibono1225 

1. Can we make the breadcrumb say "Brady Strout's Rules" as well instead of "User Rules?

**Comment by bradystroud** [comment]
Hey @tiagov8 


> 2. Is there a link I can test these changes live?

No 😕 - Ephemeral environments are awesome, but we dont have them on rules, just the website right now

Once this PR is merged, the changes will be live on staging to test

**Comment by tiagov8** [comment]
Hi @Aibono1225 

Thinking again...

What about:

> SSW > SSW Rules > Brady Strout's Rules
> 
> ## Brady Strout's Rules
> 
> ### Last Modified 
> 
> {{ LIST OF RULES }}
> 
> ### Acknowledged
> 
> {{ LIST OF RULES }}

... so we don't repeat the name so many times. As per DRY

**Comment by Aibono1225** [comment]
Here the new UI after implementing new requests. 🙂

image

**Review by bradystroud — APPROVED** [review]

**Pull request merged**
